# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SideBar.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(323, 434)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sideBar = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sideBar.sizePolicy().hasHeightForWidth())
        self.sideBar.setSizePolicy(sizePolicy)
        self.sideBar.setStyleSheet("")
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sideBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.closeSide = QtWidgets.QPushButton(self.sideBar)
        self.closeSide.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.closeSide.sizePolicy().hasHeightForWidth())
        self.closeSide.setSizePolicy(sizePolicy)
        self.closeSide.setMaximumSize(QtCore.QSize(20, 16777215))
        self.closeSide.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeSide.setFocusPolicy(QtCore.Qt.NoFocus)
        self.closeSide.setObjectName("closeSide")
        self.horizontalLayout.addWidget(self.closeSide)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_time = QtWidgets.QHBoxLayout()
        self.title_time.setObjectName("title_time")
        self.lineEdit = QtWidgets.QLineEdit(self.sideBar)
        self.lineEdit.setObjectName("lineEdit")
        self.title_time.addWidget(self.lineEdit, 0, QtCore.Qt.AlignLeft)
        self.label = QtWidgets.QLabel(self.sideBar)
        self.label.setObjectName("label")
        self.title_time.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.title_time)
        self.genre = ExLineEdit(self.sideBar)
        self.genre.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.genre.setReadOnly(True)
        self.genre.setObjectName("genre")
        self.verticalLayout.addWidget(self.genre)
        self.link = ExLineEdit(self.sideBar)
        self.link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.link.setReadOnly(True)
        self.link.setObjectName("link")
        self.verticalLayout.addWidget(self.link)
        self.desc = ExTextEdit(self.sideBar)
        self.desc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.desc.setTabChangesFocus(True)
        self.desc.setDocumentTitle("")
        self.desc.setReadOnly(True)
        self.desc.setObjectName("desc")
        self.verticalLayout.addWidget(self.desc)
        self.save = QtWidgets.QPushButton(self.sideBar)
        self.save.setEnabled(False)
        self.save.setMaximumSize(QtCore.QSize(16777215, 23))
        self.save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)
        self.is_con = QtWidgets.QCheckBox(self.sideBar)
        self.is_con.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.is_con.setFocusPolicy(QtCore.Qt.NoFocus)
        self.is_con.setObjectName("is_con")
        self.verticalLayout.addWidget(self.is_con)
        self.is_finished = QtWidgets.QCheckBox(self.sideBar)
        self.is_finished.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.is_finished.setFocusPolicy(QtCore.Qt.NoFocus)
        self.is_finished.setObjectName("is_finished")
        self.verticalLayout.addWidget(self.is_finished)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.sideBar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.closeSide.setText(_translate("Form", "<"))
        self.label.setText(_translate("Form", "ASDDASDASD"))
        self.genre.setPlaceholderText(_translate("Form", "Жанр"))
        self.link.setPlaceholderText(_translate("Form", "Ссылка"))
        self.desc.setPlaceholderText(_translate("Form", "Описание"))
        self.save.setText(_translate("Form", "Сохранить"))
        self.is_con.setText(_translate("Form", "Это продолжение"))
        self.is_finished.setText(_translate("Form", "Тайтл не закончен"))

from ExObjects import ExLineEdit, ExTextEdit

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

