# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './/RowButtons.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_row_btns(object):
    def setupUi(self, row_btns):
        row_btns.setObjectName("row_btns")
        row_btns.resize(899, 33)
        self.horizontalLayout = QtWidgets.QHBoxLayout(row_btns)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_frame = QtWidgets.QFrame(row_btns)
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.viewed = QtWidgets.QPushButton(self.left_frame)
        self.viewed.setGeometry(QtCore.QRect(120, 1, 151, 30))
        self.viewed.setMinimumSize(QtCore.QSize(30, 30))
        self.viewed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.viewed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewed.setObjectName("viewed")
        self.viewing = QtWidgets.QPushButton(self.left_frame)
        self.viewing.setGeometry(QtCore.QRect(0, 1, 115, 30))
        self.viewing.setMinimumSize(QtCore.QSize(115, 30))
        self.viewing.setMaximumSize(QtCore.QSize(100, 16777215))
        self.viewing.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewing.setFocusPolicy(QtCore.Qt.NoFocus)
        self.viewing.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.viewing.setObjectName("viewing")
        self.episode_edit = QtWidgets.QLineEdit(self.left_frame)
        self.episode_edit.setGeometry(QtCore.QRect(337, 4, 50, 25))
        self.episode_edit.setMaxLength(4)
        self.episode_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.episode_edit.setObjectName("episode_edit")
        self.minus = QtWidgets.QPushButton(self.left_frame)
        self.minus.setGeometry(QtCore.QRect(311, 4, 25, 25))
        self.minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.minus.setObjectName("minus")
        self.plus = QtWidgets.QPushButton(self.left_frame)
        self.plus.setGeometry(QtCore.QRect(388, 4, 25, 25))
        self.plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plus.setObjectName("plus")
        self.favorite_btn = QtWidgets.QPushButton(self.left_frame)
        self.favorite_btn.setGeometry(QtCore.QRect(276, 1, 30, 30))
        self.favorite_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.favorite_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.favorite_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../icons/favorite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.favorite_btn.setIcon(icon)
        self.favorite_btn.setIconSize(QtCore.QSize(25, 25))
        self.favorite_btn.setObjectName("favorite_btn")
        self.horizontalLayout.addWidget(self.left_frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.move_btn = QtWidgets.QPushButton(row_btns)
        self.move_btn.setEnabled(True)
        self.move_btn.setMinimumSize(QtCore.QSize(130, 30))
        self.move_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.move_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.move_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.move_btn.setObjectName("move_btn")
        self.horizontalLayout_3.addWidget(self.move_btn)
        self.find_btn = QtWidgets.QPushButton(row_btns)
        self.find_btn.setEnabled(True)
        self.find_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.find_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.find_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.find_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.find_btn.setObjectName("find_btn")
        self.horizontalLayout_3.addWidget(self.find_btn)
        self.del_title = QtWidgets.QPushButton(row_btns)
        self.del_title.setMinimumSize(QtCore.QSize(0, 30))
        self.del_title.setMaximumSize(QtCore.QSize(100, 16777215))
        self.del_title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_title.setFocusPolicy(QtCore.Qt.NoFocus)
        self.del_title.setObjectName("del_title")
        self.horizontalLayout_3.addWidget(self.del_title)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(row_btns)
        QtCore.QMetaObject.connectSlotsByName(row_btns)

    def retranslateUi(self, row_btns):
        _translate = QtCore.QCoreApplication.translate
        row_btns.setWindowTitle(_translate("row_btns", "Form"))
        self.viewed.setText(_translate("row_btns", "ПРОСМОТРЕНО"))
        self.viewing.setText(_translate("row_btns", "СМОТРЮ"))
        self.episode_edit.setText(_translate("row_btns", "9999"))
        self.minus.setText(_translate("row_btns", "-"))
        self.plus.setText(_translate("row_btns", "+"))
        self.move_btn.setToolTip(_translate("row_btns", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Переместить тайтл в другой плейлист</span></p></body></html>"))
        self.move_btn.setText(_translate("row_btns", "ПЕРЕМЕСТИТЬ"))
        self.find_btn.setToolTip(_translate("row_btns", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Найти в основном плейлисте</span></p></body></html>"))
        self.find_btn.setText(_translate("row_btns", "НАЙТИ"))
        self.del_title.setText(_translate("row_btns", "УДАЛИТЬ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    row_btns = QtWidgets.QWidget()
    ui = Ui_row_btns()
    ui.setupUi(row_btns)
    row_btns.show()
    sys.exit(app.exec_())
