# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\\New_Title.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(578, 91)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setAutoFillBackground(True)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.t_row = QtWidgets.QFrame(Form)
        self.t_row.setEnabled(True)
        self.t_row.setMinimumSize(QtCore.QSize(0, 0))
        self.t_row.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.t_row.setFrameShadow(QtWidgets.QFrame.Raised)
        self.t_row.setObjectName("t_row")
        self.row_layout = QtWidgets.QVBoxLayout(self.t_row)
        self.row_layout.setContentsMargins(0, 0, 0, 0)
        self.row_layout.setSpacing(5)
        self.row_layout.setObjectName("row_layout")
        self.hor_layout = QtWidgets.QHBoxLayout()
        self.hor_layout.setSpacing(0)
        self.hor_layout.setObjectName("hor_layout")
        self.status = QtWidgets.QLabel(self.t_row)
        self.status.setMinimumSize(QtCore.QSize(30, 30))
        self.status.setText("")
        self.status.setObjectName("status")
        self.hor_layout.addWidget(self.status)
        self.count = QtWidgets.QLineEdit(self.t_row)
        self.count.setMinimumSize(QtCore.QSize(0, 30))
        self.count.setMaximumSize(QtCore.QSize(100, 16777215))
        self.count.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.count.setAlignment(QtCore.Qt.AlignCenter)
        self.count.setReadOnly(True)
        self.count.setObjectName("count")
        self.hor_layout.addWidget(self.count)
        self.title_name = QtWidgets.QLineEdit(self.t_row)
        self.title_name.setEnabled(True)
        self.title_name.setMinimumSize(QtCore.QSize(0, 30))
        self.title_name.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.title_name.setText("")
        self.title_name.setDragEnabled(False)
        self.title_name.setReadOnly(True)
        self.title_name.setObjectName("title_name")
        self.hor_layout.addWidget(self.title_name)
        self.row_layout.addLayout(self.hor_layout)
        self.btns = QtWidgets.QHBoxLayout()
        self.btns.setContentsMargins(3, -1, 2, 3)
        self.btns.setSpacing(5)
        self.btns.setObjectName("btns")
        self.row_left = QtWidgets.QHBoxLayout()
        self.row_left.setObjectName("row_left")
        self.viewing = QtWidgets.QPushButton(self.t_row)
        self.viewing.setMinimumSize(QtCore.QSize(100, 30))
        self.viewing.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.viewing.setFont(font)
        self.viewing.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewing.setFocusPolicy(QtCore.Qt.NoFocus)
        self.viewing.setObjectName("viewing")
        self.row_left.addWidget(self.viewing)
        self.mark = QtWidgets.QComboBox(self.t_row)
        self.mark.setMinimumSize(QtCore.QSize(0, 30))
        self.mark.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mark.setFont(font)
        self.mark.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mark.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mark.setCurrentText("")
        self.mark.setIconSize(QtCore.QSize(30, 30))
        self.mark.setObjectName("mark")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/viewed (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mark.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icons/continuation.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mark.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Icons/pause.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mark.addItem(icon2, "")
        self.row_left.addWidget(self.mark)
        self.viewed = QtWidgets.QPushButton(self.t_row)
        self.viewed.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.viewed.setFont(font)
        self.viewed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.viewed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.viewed.setObjectName("viewed")
        self.row_left.addWidget(self.viewed)
        self.btns.addLayout(self.row_left)
        self.row_right = QtWidgets.QHBoxLayout()
        self.row_right.setObjectName("row_right")
        self.delT = QtWidgets.QPushButton(self.t_row)
        self.delT.setMinimumSize(QtCore.QSize(0, 30))
        self.delT.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delT.setFont(font)
        self.delT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delT.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delT.setObjectName("delT")
        self.row_right.addWidget(self.delT)
        self.btns.addLayout(self.row_right)
        self.row_layout.addLayout(self.btns)
        self.verticalLayout.addWidget(self.t_row)

        self.retranslateUi(Form)
        self.mark.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.viewing.setText(_translate("Form", "СМОТРЮ"))
        self.mark.setItemText(0, _translate("Form", "Просмотрен"))
        self.mark.setItemText(1, _translate("Form", "Будет продолжение"))
        self.mark.setItemText(2, _translate("Form", "Просмотр брошен"))
        self.viewed.setText(_translate("Form", "ПРОСМОТРЕНО"))
        self.delT.setText(_translate("Form", "УДАЛИТЬ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

