SEARCH_DIR(D:\Programs\HiAsm\Elements\delphi\code\)
INPUT(
wprt0.o
D:\Programs\HiAsm\Elements\delphi\code\allres.or
)
GROUP(
D:\Programs\HiAsm\Elements\delphi\code\units\libphiMultiBase.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiIcon.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiEditMulti.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpIf_arg.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpWinList.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiIndexManager.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiIconsManager.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiBoxDrawManager.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpLWinList.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiRGN_OutlinePicture.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiLayoutSpacer.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpWinLayout.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiHintManager.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpDebug.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpWinSock.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpShlObj.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpcommdlg.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpShellAPI.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpRichEdit.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiTransparentManager.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpmessages.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpWin.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiMultiElement_4BB77F0.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiMultiElement_4BB7690.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiIndexToChanel.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiCheckBox.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiWinExec.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiIf_else.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiSwitch.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiMultiElement.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiTrayIcon.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiTime.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiLED.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiLabel.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiHub.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiDoData.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiMemory.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiGetIndexData.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiComboBox.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiEdit.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiCase.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiFormatStr.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiButton.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiImage.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiTimer.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiListBox.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiPing.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiMainForm.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpShare.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpkol.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpWindows.a
D:\Programs\HiAsm\Elements\delphi\code\units\libphiMainForm_4BE3820.a
libpobjpas.a
libpsystem.a
D:\Programs\HiAsm\Elements\delphi\code\units\libpAutoPing.a
)
